name: audio_player
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^3.0.1
  file_picker: ^5.2.5
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
  marquee: ^2.2.3
  cached_network_image: ^3.2.3
  uuid: ^3.0.7
  url_launcher: ^6.1.10
  share_plus: ^6.3.1
  connectivity_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
